// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmCsk0oPVIeoz6AW_z3t_b0AjOMc5sh_Q',
    appId: '1:416020859792:web:2dcb34ac808cb1b9df0115',
    messagingSenderId: '416020859792',
    projectId: 'todo-cbae5',
    authDomain: 'todo-cbae5.firebaseapp.com',
    storageBucket: 'todo-cbae5.firebasestorage.app',
    measurementId: 'G-0BL6Z8JCP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiryh2QwoK8wiyceYh0P88bpY6SLyyxz4',
    appId: '1:416020859792:android:c993d90d5881a63ddf0115',
    messagingSenderId: '416020859792',
    projectId: 'todo-cbae5',
    storageBucket: 'todo-cbae5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl4Oh0DawIEwYiw3fF41Zn-4J6zOF1yqI',
    appId: '1:416020859792:ios:629cf2e358d59e04df0115',
    messagingSenderId: '416020859792',
    projectId: 'todo-cbae5',
    storageBucket: 'todo-cbae5.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl4Oh0DawIEwYiw3fF41Zn-4J6zOF1yqI',
    appId: '1:416020859792:ios:629cf2e358d59e04df0115',
    messagingSenderId: '416020859792',
    projectId: 'todo-cbae5',
    storageBucket: 'todo-cbae5.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmCsk0oPVIeoz6AW_z3t_b0AjOMc5sh_Q',
    appId: '1:416020859792:web:b5b691679afdd06cdf0115',
    messagingSenderId: '416020859792',
    projectId: 'todo-cbae5',
    authDomain: 'todo-cbae5.firebaseapp.com',
    storageBucket: 'todo-cbae5.firebasestorage.app',
    measurementId: 'G-KWW1ZDEZ62',
  );
}
